
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "root" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "root" } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "mp_development" } %>

dev_https:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "mp_dev_https" } %>

staging:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "mp_staging" } %>

test:
  <<: *default
  database: mp_test
  username: postgres
  password: ""
  host: localhost

production:
  url: <%= ENV["DATABASE_URL"] %>
  host: <%= ENV["DB_HOST"] %>
  adapter: postgresql
