name: Frontend CI

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn

      - name: Auth to GitHub Package Registry
        run: |
          echo "@nessprim:registry=https://npm.pkg.github.com" >> ~/.yarnrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" >> ~/.yarnrc

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint code
        run: yarn eslint .

      - name: Run tests
        run: yarn test --ci --watchAll=false

      - name: Build app (optional)
        run: yarn build
