name: Frontend CI

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./client
        env:
          NODE_AUTH_TOKEN: ${{ vars.NODE_AUTH_TOKEN }}

      - name: Run ESLint
        run: npx eslint .
        working-directory: ./client

      - name: Run tests
        run: npm test
        working-directory: ./client
